name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
 
sdcard/
User's shared internal storage.
bash: /: Is a directory
bash: data/: No such file or directory
[1] 14717
No command Contains found, did you mean:
 Command fontlint in package fontforge-gtk from the x11-repo repository
 Command fontinst in package texlive-bin
No command apps. found, did you mean:
 Command apxs in package apache2
 Command apsw in package python-apsw
[1]+  Exit 127                   Contains user data
bash: app/: No such file or directory
User-installed: command not found
bash: system/: No such file or directory
No command Core found, did you mean:
 Command bore in package bore
 Command more in package util-linux
bash: app/: No such file or directory
Pre-installed: command not found
bash: priv-app/: No such file or directory
Privileged: command not found
bash: sdcard/: No such file or directory       npx webpack
